### ISSUE TITLE
“No OpKernel was registered to support Op”  can this code run on GPU ?

### ISSUE THREAD

**Issue by WHJTC** [salesforce/ctrl#22]
I encountered this error when I run this code on GPU

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
File "/data/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
return fn(*args)
File "/data/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1339, in _run_fn
self._extend_graph()
File "/data/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _extend_graph
tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CrossReplicaSum' used by {{node training/CrossReplicaSum}}with these attrs: [T=DT_FLOAT, _class=["loc:@training/gradients/concat"]]
Registered devices: [CPU, GPU, XLA_CPU, XLA_GPU]
Registered kernels:
<no registered kernels>

**Comment by BangLiu** [comment]
I also have this problem. Any ideas about how to solve it? Thanks!

**Comment by keskarnitish** [comment]
It seems that you didn't follow Step 2 (patching) of the usage. If problem persists, please reopen this issue.
